= Data Science Portfolio

_By Graeme West_



This repository contains a variety of data science projects and explorations that I've done for personal development.

You can browse the list below, or click the Binder button below to launch the whole repository there. Note that this will probably only work for the Python projects with Jupyter notebooks

image::https://mybinder.org/badge_logo.svg[link=https://mybinder.org/v2/gh/capncodewash/DataSciencePortfolio/master]

== List of projects

* *Word Frequency in Moby Dick (DataCamp)*
+
This project uses the nltk toolkit to describe approximate word frequencies in the text of Herman Melville's novel Moby Dick, accounting for English stop words.
+
Technologies and techniques used:
+
Python, nltk, matplotlib, Jupyter notebooks.
+
Links:
+
** https://github.com/capncodewash/DataSciencePortfolio/blob/master/DataCamp_Word_Frequency_in_Moby_Dick/notebook.ipynb[View on GitHub]
** https://mybinder.org/v2/gh/capncodewash/DataSciencePortfolio/master?filepath=DataCamp_Word_Frequency_in_Moby_Dick%2Fnotebook.ipynb[View on Binder]

* *A Network Analysis of Game of Thrones (DataCamp)*
+
A graph analysis project. By calculating different measures of network effects for major characters from the Game of Thrones books, this project seeks to determine the most important characters in each book. The measures used are the Google PageRank algorithm, betweenness centrality, and degree centrality.
+
Technolgies and techniques used:
+
Python, networkx, pandas, Jupyter notebooks.
+
Links:
+
** https://github.com/capncodewash/DataSciencePortfolio/blob/master/DataCamp_A_Network_analysis_of_Game_of_Thrones/notebook.ipynb[View on GitHub]
** https://mybinder.org/v2/gh/capncodewash/DataSciencePortfolio/master?filepath=DataCamp_A_Network_analysis_of_Game_of_Thrones%2Fnotebook.ipynb[View on Binder]

* *Reducing Traffic Mortality in the USA (DataCamp)*
+
A project involving exploratory data analysis (EDA) and cluster analysis using the KMeans algorithm. The subject matter is CSV data covering mortality rates in traffic data.
+
Technologies and techniques used:
+
Python, scikit-learn, pandas, matplotlib, KMeans clustering, EDA
+
Links:
+
** https://github.com/capncodewash/DataSciencePortfolio/blob/master/DataCamp_Reducing_Traffic_Mortality_in_the_USA/notebook.ipynb[View on GitHub]
** https://mybinder.org/v2/gh/capncodewash/DataSciencePortfolio/master?filepath=DataCamp_Reducing_Traffic_Mortality_in_the_USA%2Fnotebook.ipynb[View on Binder]

* *Bad Passwords and the NIST Guidelines (DataCamp)*
+
A project involving manipulation of Pandas dataframes to introduce new columns denoting particular negative properties of the passwords. By creating Pandas series containing the results of Boolean expressions on the contents, we can select rows and create subsets.
+
Technologies and techniques used:
+
Python, pandas
+
Links:
+
** https://github.com/capncodewash/DataSciencePortfolio/blob/master/DataCamp_Bad_passwords_and_the_NIST_guidelines/notebook.ipynb[View on GitHub]
** https://mybinder.org/v2/gh/capncodewash/DataSciencePortfolio/master?filepath=DataCamp_Bad_passwords_and_the_NIST_guidelines%2Fnotebook.ipynb[View on Binder]

* *Classifying Song Genres from Audio Data (DataCamp)*
+
In this project, we use the EchoNest dataset to predict the genre of songs from certain metadata characteristics, for example 'tempo' and 'energy'. We compare and evaluate the outputs of logistic regression and a decision tree classifier using K-fold cross-validation.
+
Technologies and techniques used:
+
Python, logistic regression, decision trees, K-fold cross validation, scikit-learn
+
** https://github.com/capncodewash/DataSciencePortfolio/blob/master/DataCamp_Classify_Song_Genres_from_Audio_Data/notebook.ipynb[View on GitHub]
** https://mybinder.org/v2/gh/capncodewash/DataSciencePortfolio/master?filepath=DataCamp_Classify_Song_Genres_from_Audio_Data%2Fnotebook.ipynb[View on Binder]