= Data Science Portfolio

_By Graeme West_



This repository contains a variety of data science projects and explorations that I've done for personal development.

== List of projects

* *Word Frequency in Moby Dick (DataCamp)*
+
This project uses the nltk toolkit to describe approximate word frequencies in the text of Herman Melville's novel Moby Dick, accounting for English stop words.
+
Technologies and techniques used:
+
Python, nltk, matplotlib, Jupyter notebooks.
+
Links:
+
** https://github.com/capncodewash/DataSciencePortfolio/blob/master/DataCamp_Word_Frequency_in_Moby_Dick/notebook.ipynb[View on GitHub]
** https://hub.mybinder.org/user/capncodewash-da-cienceportfolio-06z2x2d8/notebooks/DataCamp_Word_Frequency_in_Moby_Dick/notebook.ipynb[View on Binder]

* *A Network Analysis of Game of Thrones (DataCamp)*
+
A graph analysis project. By calculating different measures of network effects for major characters from the Game of Thrones books, this project seeks to determine the most important characters in each book. The measures used are the Google PageRank algorithm, betweenness centrality, and degree centrality.
+
Technolgies nad techniques used:
+
Python, networkx, pandas, Jupyter notebooks.
+
Links:
+
** https://github.com/capncodewash/DataSciencePortfolio/blob/master/A_Network_analysis_of_Game_of_Thrones/notebook.ipynb[View on GitHub]
** https://hub.mybinder.org/user/capncodewash-da-cienceportfolio-06z2x2d8/notebooks/A_Network_analysis_of_Game_of_Thrones/notebook.ipynb[View on Binder]
